---
title: "Export"
output: html_notebook
---

```{r}
vattenkemi_data %>%
  select(1:5) %>%
  distinct() %>%
  full_join(trends %>%
              ungroup %>%
              select(1:3) %>%
              distinct) %>%
  left_join(joined_dataset %>%
              select(1:5, `MS_CD C3`) %>% distinct()) %>%
  arrange(`MD-MVM Id`) %>%
  write_excel_csv("allasjoar_test.csv")

#vattendragkemi_mannkendall %>%
#  select(1:3) %>%
#  distinct() %>%
#  left_join(trendvattendrag_kemi %>%
#              select(1:5, `MS_CD C3`) %>% distinct()) %>%
#  write_excel_csv("allavattendrag.csv")
```

# Kodbok och variabelnamn
```{r}
Import_variabler_sotvatten <- read_excel(here("Annat/Import variabler sotvatten.xlsx"), # ö till o
                                         col_types = c("text", "text", "text",
                                                       "skip", "text", "skip", "skip",
                                                       "text", "skip", "text", "skip"))

codebook <- tibble::tribble(
                                         ~`DATA ID`,               ~variable,
                                    "Klorofyll a",                "Kfyll (µg/l)",
                    "Total biovolym växtplankton",            "Biovolym (mm3/l)",
                 "Biovolym cyanobakterier totalt",       "Cyanobacteria (mm3/l)",
                                         "Sulfat",             "SO4_IC (mekv/l)",
                                    "Totalfosfor",                "Tot-P (µg/l P)",
                                     "Totalkväve",                "Tot-N (µg/l N)",
                          "Lättillgänglig fosfor",                "PO4-P (µg/l P)",
                               "Oorganiskt kväve",         "Oorganiskt N (µg/l N)",
                           "Totalt organiskt kol",                  "TOC (mg/l C)",
                                          "Kisel",                   "Si (µg/l)",
                            "Temperatur ytvatten",         "Temperatur ytvatten",
                                       "Siktdjup",                "Siktdjup (m)",
                                    "Alkalinitet",        "Alkalinitet (mekv/l)",
                                        "Brunhet",            "Abs_F 420 (/5cm)",
                                             "pH",                          "pH",
              "Total kvävebelastning  till havet",                   "Tot_N ton",
         "Belastning oorganiskt kväve till havet",                "Oorganiskt N",
              "Total fosforbelastning till havet",                   "Tot-P ton",
    "Belastning lättillgänglig fosfor till havet",                   "PO4-P ton",
      "Total belastning organiskt kol till havet",                     "TOC ton",
                           "Insjöfisk totalmängd",        "Insjöfisk totalmängd",
                          "Insjöfisk antal arter",       "Insjöfisk antal arter",
                              "Insjöfisk abborre",      	   "Insjöfisk abborre",
                                "Insjöfisk gädda",       	     "Insjöfisk gädda",
                                 "Insjöfisk mört",       	      "Insjöfisk mört",
                               "Insjöfisk röding",      	    "Insjöfisk röding",
                     "Vattendrag totalmängd fisk",	"Vattendrag totalmängd fisk",
                                 "Vattendrag lax",	            "Vattendrag lax",
                               "Vattendrag öring",          	"Vattendrag öring",
                         "Vattendrag antal arter",	    "Vattendrag antal arter",
                                 "Medelavrinning",                      "medelq"
                          )
```

# Sjöar
## Växtplankton
```{r}
vaxtplankton_var <- vaxtplankton_mannkendall %>%
  select(variable) %>%
  distinct() %>%
  left_join(codebook) %>%
  left_join(Import_variabler_sotvatten) %>%
  rename(`VariabelID` = `DATA ID`)
```

### Mann-Kendall
```{r}
vaxtplankton_mannkendall %>%
  full_join(vaxtplankton_var) %>%
  left_join(joined_dataset %>%
              select(1:5, `MS_CD C3`) %>% distinct()) %>%
  transmute(VattenID = `EU id`, 
            Vattenkategori = "Station", 
            VariabelID,
            `Trendens signifikans` = case_when(p.value < 0.05 & slope > 0 ~ 1,
                                               p.value < 0.05 & slope < 0 ~ -1,
                                               p.value > 0.05 ~ 0),
            `p-värde` = p.value,
            `Medianförändring per år` = slope)%>%
  write_excel_csv("Outdata2019\\vaxtplankton_status.csv", 
                  na = "")


```

### Trender

```{r}
trends  %>%
  select(-fit) %>% 
  spread(type, value) %>%
  full_join(vaxtplankton_var) %>%
  left_join(joined_dataset %>%
              select(1:5, 
                     `MS_CD C3`, Regionala) %>% 
              distinct()) %>%
  ungroup() %>%
  transmute(VattenID = `EU id`, 
            Vattenkategori = "Station", 
            VariabelID, 
            Bedömningsår = Provtagningsår,
            Årsvärde = value, 
            Standardfel = NA, 
            Trendvärde = trend, 
            `Antal provtagningstillfällen` = n,
            `Andel regionala data` = Regionala) %>%
  write_excel_csv("Outdata2019\\vaxtplankton_serier.csv",
                  na = "")
```

## Vattenkemi
```{r}
vattenkemi_sjo_var <- kemi_sjo_mannkendall %>%
  select(variable) %>%
  distinct() %>%
  left_join(codebook) %>%
  left_join(Import_variabler_sotvatten) %>%
  rename(`VariabelID` = `DATA ID`)
```

### Mann-Kendall
```{r}
kemi_sjo_mannkendall %>%
  full_join(vattenkemi_sjo_var) %>%
  left_join(joined_dataset %>%
              select(1:5, 
                     `MS_CD C3`) %>% 
              distinct()) %>%
  transmute(VattenID = `EU id`, 
            Vattenkategori = "Station", 
            VariabelID,
            `Trendens signifikans` = case_when(p.value < 0.05 & slope > 0 ~ 1,
                                               p.value < 0.05 & slope < 0 ~ -1,
                                               p.value > 0.05 ~ 0),
            `p-värde` = p.value,
            `Medianförändring per år` = slope) %>%
  write_excel_csv("Outdata2019\\sjo_kemi_status.csv",
                  na = "")
```

### Trender

```{r}
kemi_sjo_trender %>%
  select(-fit) %>% 
  full_join(vattenkemi_sjo_var) %>%
  left_join(joined_dataset %>%
              select(1:5, 
                     `MS_CD C3`, Regionala) %>% 
              distinct())  %>%
 # ungroup %>%
  transmute(VattenID = `EU id`, 
            Vattenkategori = "Station", 
            VariabelID, 
            Bedömningsår = year,
            Årsvärde = value, 
            Standardfel = NA, 
            Trendvärde = trend, 
            `Antal provtagningstillfällen` = n,
            `Andel regionala data` = Regionala) %>% 
  filter(!is.na(VariabelID)) %>%
  write_excel_csv("Outdata2019\\sjo_kemi_serier.csv", 
                  na = "")
```

# Vattendrag
## Vattenkemi
```{r}
vattendrag_kemi_vars <- vattendragkemi_mannkendall %>%
  select(variable) %>%
  distinct() %>%
  left_join(codebook) %>%
  left_join(Import_variabler_sotvatten) %>%
  rename(`VariabelID` = `DATA ID`)
```

### Mann-Kendall
```{r}
vattendragkemi_mannkendall %>%
  full_join(vattendrag_kemi_vars) %>%
  left_join(trendvattendrag_kemi_data %>%
              select(1:5, 
                     `MS_CD C3`) %>% 
              distinct()) %>%
  transmute(VattenID = `EU id`, 
            Vattenkategori = "Station", 
            VariabelID,
            `Trendens signifikans` = case_when(p.value < 0.05 & slope > 0 ~ 1,
                                               p.value < 0.05 & slope < 0 ~ -1,
                                               p.value > 0.05 ~ 0),
            `p-värde` = p.value,
            `Medianförändring per år` = slope) %>%
  write_excel_csv("Outdata2019\\vattendrag_vattenkemi_status.csv",
                  na = "")
```

### Trender

```{r}
gam_models_vattendrag_kemi %>%
  select(-fit) %>% 
  full_join(vattendrag_kemi_vars) %>%
  left_join(trendvattendrag_kemi_data %>%
              select(1:5, 
                     `MS_CD C3`) %>% 
              distinct()) %>%
  transmute(VattenID = `EU id`, 
            Vattenkategori = "Station", 
            VariabelID, 
            Bedömningsår = Provtagningsår,
            Årsvärde = value, 
            Standardfel = NA, 
            Trendvärde = trend, 
            `Antal provtagningstillfällen` = n,
            `Andel regionala data` = 0) %>% 
  filter(!is.na(VariabelID)) %>%
  write_excel_csv("Outdata2019\\vattendrag_vattenkemi_serier.csv", na = "")
```

# Flodmynningar

```{r}
flodmynningar_vars <- Belastningar_mannkendall_stationer %>%
  select(variable) %>%
  distinct() %>%
  left_join(codebook) %>%
  left_join(Import_variabler_sotvatten) %>%
  rename(`VariabelID` = `DATA ID`)

stationer_flodmynningar <- read_delim(here("Koordinatfiler/stationer_flodmynningar.csv"),
                                      ",", 
                                      escape_double = FALSE, 
                                      locale = locale(encoding = "WINDOWS-1252"),
                                      trim_ws = TRUE)

#stationer_flodmynningar %>%
#  right_join(belastningar_fitted_models %>%
#               rename(trend = predicted))
```

## Mann-Kendall
```{r}
Belastningar_mannkendall_stationer %>%
  full_join(flodmynningar_vars) %>%
  left_join(stationer_flodmynningar) %>%
  transmute(Stationsnamn = StnNamn, 
            #Havsområde = Område,
            #Flodområde,
            #VattenID = `MS_CD C3`, 
            VattenID=StationsID,
            Vattenkategori = "Flodmynning",
            VariabelID,
            `Trendens signifikans` = case_when(p.value < 0.05 & slope > 0 ~ 1,
                                               p.value < 0.05 & slope < 0 ~ -1,
                                               p.value > 0.05 ~ 0),
            `p-värde` = p.value,
            `Medianförändring per år` = slope) %>%
  write_excel_csv("Outdata2019\\flodmynningar_belastningar_status.csv",
                  na = "")
```

## Trender
```{r}
belastningar_fitted_models %>%
  full_join(flodmynningar_vars) %>%
  left_join(stationer_flodmynningar) %>%
  transmute(#Havsområde = Område,
            #Flodområde,
            #Stationsnamn = StnNamn,
            # VattenID = `MS_CD C3`,
            VattenID=StationsID,
            Vattenkategori = "Flodmynning",
            VariabelID,
            Bedömningsår = År,
            #`Medelavrinning [m3/s]` = `Medel_Q m3/s`,
            #`Flödesstandardiserad belastning` = flow_stand_value,
            Årsvärde = value,
            Standardfel = NA,
            Trendvärde = predicted,
            `Antal provtagningstillfällen` = NA,
            `Andel regionala data` = NA) %>% 
  filter(!is.na(VariabelID)) %>%
  write_excel_csv("Outdata2019\\flodmynningar_belastningar_serier.csv", 
                  na = "")
```

# Fiske i sjöar och vattendrag
## Sjöar
```{r}
fisk_var <- fisk_mannkendall %>%
  select(variable) %>%
  distinct() %>%
  left_join(codebook) %>%
  left_join(Import_variabler_sotvatten) %>%
  rename(`VariabelID` = `DATA ID`)
```

### Mann-Kendall
```{r}
fisk_mannkendall %>%
  full_join(fisk_var) %>%
  left_join(fisk_sjo %>%
              select(`Stationsnamn`, 
                     MS_CD, 
                     EU_CD, 
                     `Stationskoordinat N/X`, 
                     `Stationskoordinat E/Y`) %>% 
              distinct()) %>%
  transmute(VattenID = `EU_CD`, 
            Vattenkategori = "Station", 
            VariabelID,
            `Trendens signifikans` = 
              case_when(`VariabelID` != "Insjöfisk antal arter" & p.value < 0.05 & slope > 0 ~ 1,
                        `VariabelID` != "Insjöfisk antal arter" & p.value < 0.05 & slope < 0 ~ -1,
                        `VariabelID` != "Insjöfisk antal arter" & p.value > 0.05 ~ 0),
            `p-värde` = case_when(`VariabelID` != "Insjöfisk antal arter" ~ `p.value`),
            `p-värde` = case_when(`EU_CD`==as.character("NW683582-154935") ~ NA_real_,
                                  `EU_CD`==as.character("SE663532-148571") ~ NA_real_,
                                  `EU_CD`==as.character("SE670275-146052") ~ NA_real_,
                                  TRUE ~`p-värde`),
            `Medianförändring per år` = case_when(`VariabelID` != "Insjöfisk antal arter" ~ slope),
            `Medianförändring per år` = case_when(`EU_CD`=="NW683582-154935" ~ NA_real_,
                                                  `EU_CD`=="SE663532-148571" ~ NA_real_,
                                                  `EU_CD`=="SE670275-146052" ~ NA_real_,
                                                  TRUE ~ `Medianförändring per år`)) %>%
  write_excel_csv("Outdata2019\\fisk_status.csv", na = "")
```

### Trender

```{r}
fisk_sjo_trends  %>%
  select(-fit) %>% 
  spread(type, value) %>%
  full_join(fisk_var) %>%
  left_join(fisk_sjo %>%
              select(`Stationsnamn`, 
                     MS_CD, 
                     EU_CD, 
                     `Stationskoordinat N/X`, 
                     `Stationskoordinat E/Y`) %>% 
              distinct()) %>%
  ungroup %>%
  transmute(VattenID = `EU_CD`, 
            Vattenkategori = "Station", 
            VariabelID, 
            Bedömningsår = Provtagningsår,
            Årsvärde = value, 
            Standardfel = NA,
            Trendvärde = case_when(VariabelID != "Insjöfisk antal arter" ~ trend),
            Trendvärde =case_when(EU_CD == "NW683582-154935" ~ NA_real_,
                                  EU_CD == "SE663532-148571" ~ NA_real_,
                                  EU_CD == "SE670275-146052" ~ NA_real_,
                                  TRUE ~ Trendvärde),
            `Antal provtagningstillfällen` = n,
            `Andel regionala data` = 0) %>%
  write_excel_csv("Outdata2019\\fisk_serier.csv",
                  na = "")
```

## Vattendrag
```{r}
fisk_vdr_var <- fisk_vdr_mannkendall %>%
  select(variable) %>%
  distinct() %>%
  left_join(codebook) %>%
  left_join(Import_variabler_sotvatten) %>%
  rename(`VariabelID` = `DATA ID`)
```

### Mann-Kendall

```{r}
fisk_vdr_mannkendall %>%
  full_join(fisk_vdr_var) %>%
  left_join(fisk_vdr %>%
              select(`Stationsnamn`, 
                     `MS_CD`, 
                     `EU_CD`, 
                     `Stationskoordinat N/X`, 
                     `Stationskoordinat E/Y`) %>% 
              distinct()) %>%
  transmute(VattenID = `EU_CD`, 
            Vattenkategori = "Station", 
            VariabelID,
            `Trendens signifikans` = 
              case_when(`VariabelID` != "Vattendrag antal arter" & p.value < 0.05 & slope > 0 ~ 1,
                        `VariabelID` != "Vattendrag antal arter" & p.value < 0.05 & slope < 0 ~ -1,
                        `VariabelID` != "Vattendrag antal arter" & p.value > 0.05 ~ 0),
            `p-värde` = case_when(`VariabelID` != "Vattendrag antal arter" ~ `p.value`),
            `Medianförändring per år` = case_when(`VariabelID` != "Vattendrag antal arter" ~ slope)) %>%
  write_excel_csv("Outdata2019\\fisk_vdr_status.csv", na = "")
```

### Trender
```{r}
fisk_vdr_trends %>%
  select(-fit) %>% 
  spread(type, value) %>%
  full_join(fisk_vdr_var) %>%
  left_join(fisk_vdr %>%
              select(`Stationsnamn`, 
                     MS_CD, 
                     EU_CD, 
                     `Stationskoordinat N/X`, 
                     `Stationskoordinat E/Y`) %>% 
              distinct()) %>%
  ungroup() %>%
  transmute(VattenID = `EU_CD`, 
            Vattenkategori = "Station", 
            VariabelID, 
            Bedömningsår = Provtagningsår,
            Årsvärde = value, 
            Standardfel = NA,
            Trendvärde = case_when(VariabelID != "Vattendrag antal arter" ~ trend),
            `Antal provtagningstillfällen` = n,
            `Andel regionala data` = 0 ) %>%
  write_excel_csv("Outdata2019\\fisk_vdr_serier.csv",
                  na = "")
```

# Ihopslagning

## Sjöar

### Serier
```{r}
sjo_serier <- read_csv("Outdata2019\\vaxtplankton_serier.csv") %>% 
  full_join(read_csv("Outdata2019\\sjo_kemi_serier.csv")) %>% 
  full_join(read_csv("Outdata2019\\fisk_serier.csv"))
write_excel_csv(sjo_serier, "Outdata2019\\sjo_serier.csv")
```

### Mann-Kendall

```{r}
sjo_status <- read_csv("Outdata2019\\vaxtplankton_status.csv") %>% 
  full_join(read_csv("Outdata2019\\sjo_kemi_status.csv")) %>% 
  full_join(read_csv("Outdata2019\\fisk_status.csv"))
write_excel_csv(sjo_status, "Outdata2019\\sjo_status.csv")
```

## Vattendrag

### Serier
```{r}
vattendrag_serier <- read_csv("Outdata2019\\flodmynningar_belastningar_serier.csv") %>% 
  full_join(read_csv("Outdata2019\\fisk_vdr_serier.csv"))%>%
  full_join(read_csv("Outdata2019\\vattendrag_vattenkemi_serier.csv"))
write_excel_csv(vattendrag_serier, "Outdata2019\\vattendrag_serier.csv")
```

### Mann-Kendall
```{r}
vattendrag_status <- read_csv("Outdata2019\\vattendrag_vattenkemi_status.csv") %>% 
  full_join(read_delim("Outdata2019\\fisk_vdr_status.csv", 
    ",", escape_double = FALSE, locale = locale(encoding = "ISO-8859-1"), 
    trim_ws = TRUE)) # Något konstigt med teckenkodningen på vattendrag-fisk-status

write_excel_csv(vattendrag_status, "Outdata2019\\vattendrag_status.csv")
```





