---
title: "Vattenkemi - sjöar"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---
```{r echo=FALSE, message=FALSE, warning=FALSE}
#Initial inladdning av paket och egenskrivna funktioner
source("shared_functions.R")
```

```{r}
source("joined_dataset.R", encoding = "UTF-8")
```


```{r include=FALSE}
# Importera data (.txt-filer)
joined_dataset %>% 
  select(1:Provkommentar, 
         `NO2+NO3-N (µg/l)`,
         `NH4-N (µg/l)`, #Oorganiskt kväve
         `Kjeld.-N (µg/l)`, 
         `Tot-N_TNb (µg/l)`,
         `Tot-N_ps (µg/l)`, # Totalt kväve
         `Tot-N (µg/l)`,
         `Tot-P (µg/l)`, #Totalt fosfor
         `PO4-P (µg/l)`, #Fosfatfosfor
         `TOC (mg/l)`, # Totalt organiskt kol
         `Alk/Acid (mekv/l)`,
         `Alk. (mekv/l)`, #Alkalinitet
         `Siktdjup med kikare (m)`, 
         `Siktdjup utan kikare (m)`,
         `Siktdjup (m)`, # Siktdjup
         `Si (µg/l)`, # Kisel
         `Si (mg/l)`, 
         `SO4_IC (mekv/l)`, #Sulfat
         pH,
         `Abs_F 420 (/5cm)`) %>% # Brunhet
  as_tibble() %>% 
  mutate(`Oorganiskt N (µg/l)` = `NO2+NO3-N (µg/l)`+`NH4-N (µg/l)`,
    `Tot-N_TNb (µg/l)` = ifelse((Provtagningsår + (Provtagningsmånad-1)/12)>(2009+8/12), `Tot-N_TNb (µg/l)`, NA),
    `Tot-N (µg/l)` = `Tot-N_TNb (µg/l)` %>% 
      coalesce(`Kjeld.-N (µg/l)`+`NO2+NO3-N (µg/l)`) %>% 
      coalesce(`Tot-N_ps (µg/l)`) %>% 
      coalesce(`Tot-N (µg/l)`),
    `Alkalinitet (mekv/l)` = `Alk/Acid (mekv/l)` %>% coalesce(`Alk. (mekv/l)`),
    `Siktdjup (m)` = `Siktdjup med kikare (m)` %>% 
         coalesce(`Siktdjup utan kikare (m)`) %>% 
         coalesce(`Siktdjup (m)`),
    `Si (µg/l)` = `Si (µg/l)` %>% coalesce(`Si (mg/l)`/1000)) %>% 
  group_by(Stationsnamn, `Stationskoordinat N/X`, `Stationskoordinat E/Y`, Provdatum) %>% 
  filter(`Max provdjup (m)` <= 2, `Max provdjup (m)` == min(`Max provdjup (m)`)) %>%
  ungroup() %>% # Ytligaste provet som inte är djupare än 2 meter
    select(1:25, 
         `Oorganiskt N (µg/l)`,
         `Tot-N (µg/l)`,
         `Tot-P (µg/l)`, 
         `PO4-P (µg/l)`, 
         `TOC (mg/l)`,
         `Alkalinitet (mekv/l)`,
         `Siktdjup (m)`,
         `Si (µg/l)`,
         `SO4_IC (mekv/l)`,
         pH,
         `Abs_F 420 (/5cm)`) %>% 
  mutate(year = ifelse(Provtagningsmånad == 12, yes = Provtagningsår+1, no=Provtagningsår),
        season = Provtagningsmånad %>% 
          factor() %>% 
          fct_collapse("1" = c("1","2","12"),
                       "2" = c("3","4","5"),
                       "3" = c("6","7","8"),
                       "4" = c("9","10","11")) %>% as.character() %>% 
           parse_number()
         ) %>% 
  gather(variable, value, 26:(ncol(.)-2), na.rm = T) %>% # 2 due to season and year
  group_by(Stationsnamn, `Stationskoordinat N/X`, `Stationskoordinat E/Y`, variable) %>% 
  periods(year, filter_less_than = 10) %>% 
  mutate(n_years = n_distinct(year, na.rm = TRUE)) %>% 
  ungroup() -> 
  vattenkemi_data
```

```{r warning=FALSE, include=FALSE}
vattenkemi_data %>% 
  group_by(Stationsnamn, `Stationskoordinat N/X`, `Stationskoordinat E/Y`, variable, year, 
           season, 
           n_years) %>% 
  summarise(value = mean(value, na.rm = T),
            n = n()) %>% 
  ungroup() %>%
  group_by(Stationsnamn, `Stationskoordinat N/X`, `Stationskoordinat E/Y`, variable, year, 
           n_years) %>% 
  summarise(value = mean(value, na.rm = T),
            n = sum(n)) %>% 
  ungroup() %>% 
  ####### Ta säsongsmedelvärden, sen årsmedelvärden på det
  arrange(Stationsnamn, `Stationskoordinat N/X`, `Stationskoordinat E/Y`, variable, year) %>% 
    nest(data = c(-Stationsnamn, -`Stationskoordinat N/X`, -`Stationskoordinat E/Y`, -variable)) %>% 
    mutate(fit = future_map(data, 
                            possibly(~ gam(formula = value ~ s(year, k=n_distinct(.x %>% filter(!is.na(value)) %>% .$year)-2),
                                data = .x, 
                                method="REML", select=T), otherwise = NA_real_), .progress = T)) %>% 
  mutate(trend = map2(fit, data, possibly(~ predict.gam(object = .x, newdata = .y, type="response"), otherwise = NA_real_), .progress = TRUE)) %>% 
  unnest(c(data, trend)) -> 
  kemi_sjo_trender
```

```{r message=FALSE, warning=FALSE, include=FALSE}
kemi_sjo_trender %>% 
  filter(n_years >= 10, !is.na(value)) %>% 
  nest(data = c(-Stationsnamn, -variable, -`Stationskoordinat N/X`, -`Stationskoordinat E/Y`)) %>% 
  mutate(fit = map(data, possibly(~rkt(date = as.data.frame(.x)$year, 
                                       y=as.data.frame(.x)$value, correct = TRUE), otherwise=NA_real_)),
         tidy = map(fit, possibly(~rkt_out(.x), otherwise=NA_real_))) %>% 
  unnest(tidy) %>% 
  select(-data, -fit)  %>% 
  mutate(sig.stars=cut(p.value, breaks=c(1, 0.05,0.01,0.001,0.0001,0), 
                   labels=c("ns","*","**","***","****") %>% rev, ordered_result = T),
         p.value = p.value %>% round(4),
         slope = slope %>% signif(4), 
         tau = tau %>% round(4)) %>% 
         replace_na(list(sig.stars="****")) ->
  kemi_sjo_mannkendall
```




## Oorganiskt N
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Oorganiskt N (µg/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="NH4-N (µg/l)")
```
## Tot-N (µg/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Tot-N (µg/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Tot-N_ps (µg/l)")
```
## Tot-P (µg/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Tot-P (µg/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Tot-P (µg/l)")
```

## PO4-P (µg/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}

kemi_sjo_trender %>% 
  filter(variable == "PO4-P (µg/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="PO4-P (µg/l)")
```

## TOC (mg/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "TOC (mg/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="TOC (mg/l)")
```
## Alkalinitet (mekv/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Alkalinitet (mekv/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Alkalinitet (mekv/l)")
```
## Siktdjup (m)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Siktdjup (m)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Siktdjup (m)")
```
## Temperatur
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Vattentemperatur ytvatten") %>% 
  ggplot(aes(x=Provtagningsår, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Vattentemperatur ytvatten")
```
## Si (µg/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Si (µg/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Si (µg/l)")
```
## SO4_IC (mekv/l)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "SO4_IC (mekv/l)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="SO4_IC (mekv/l)")
```
## pH
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "pH") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="pH")
```
## Abs_F 420 (/5cm)
```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
kemi_sjo_trender %>% 
  filter(variable == "Abs_F 420 (/5cm)") %>% 
  ggplot(aes(x=year, y=value))+
  geom_line(linetype="dashed")+
  facet_wrap(~paste(Stationsnamn, "\r\n",`Stationskoordinat N/X`,`Stationskoordinat E/Y`), scales = "free_y", ncol = 8)+
  geom_line(aes(y=trend), linetype="solid")+
  labs(title="Abs_F 420 (/5cm)")
```


## Mann-Kendall Årsmedelvärden

```{r echo=FALSE}
kemi_sjo_mannkendall %>% datatable()
```

